version: 3
services:
  sermon-api:
    image: coventrypca/sermon-api:latest
    container_name: sermon-api
    ports:
      - "3167:3167"
    environment:
      - SA_API_KEY=
      - S3_ACCESS_KEY=
      - S3_SECRET=
      - REPO_URL=
      - GIT_USER=
      - GIT_EMAIL=
      - GIT_PASS=
      - CHANNEL_ID=
    volumes:
      - <path/on/host>:/app/data/client_secrets.json
      - <path/on/host>:/app/data/oauth2.json
    restart: unless-stopped
