---
name: Build and Push Docker Image

on:
  # Allows you to run workflow manually from Actions tab
  workflow_dispatch:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            coventrypca/sermon-api
          tags: |
            type=raw,value=latest

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
